export const aplicacoes = [
  {
    nome: 'RH',
    stack: 5,
    'ci/cd': 5,
    iac: 5,
    deployment: 5,
    custo: 5,
    logging: 3,
    tracing: 5,
    monitoring: 5,
    documentacao: 'https://doc.app.com',
    repositorio: 'https://github.com/rh-app',
    descricao: 'Descrição do RH.'
  },
  {
    nome: 'B2B',
    stack: 16,
    'ci/cd': 16,
    iac: 8,
    deployment: 8,
    custo: 16,
    logging: 5,
    monitoring: 7,
    tracing: 8,
    documentacao: 'https://doc2.app.com',
    repositorio: 'https://github.com/b2b-app',
    descricao: 'Descrição do B2B.',
  },
  {
    nome: 'Services',
    stack: 16,
    'ci/cd': 8,
    iac: 8,
    deployment: 8,
    custo: 8,
    logging: 2,
    monitoring: 4,
    tracing: 4,
    documentacao: 'https://doc3.app.com',
    repositorio: 'https://github.com/services-app',
    descricao: 'Descrição de serviços.',
  }
];